define([
    "openlayers",
    '/statics/lib/ole/lib/compat.js',
    'Editor.js',
    'Editor/Control/CleanFeature.js',
    'Editor/Control/DragFeature.js',
    'Editor/Control/DeleteFeature.js',
    'Editor/Control/DeleteAllFeatures.js',
    'Editor/Control/Dialog.js',
    'Editor/Control/DrawHole.js',
    'Editor/Control/DrawPolygon.js',
    'Editor/Control/DrawPath.js',
    'Editor/Control/DrawPoint.js',
    'Editor/Control/DrawText.js',
    'Editor/Control/DrawRegular.js',
    'Editor/Control/EditorPanel.js',
    'Editor/Control/ImportFeature.js',
    'Editor/Control/LayerSettings.js',
    'Editor/Control/MergeFeature.js',
    'Editor/Control/TransformFeature.js',
    'Editor/Control/FixedAngleDrawing.js',
    'Editor/Layer.js',
    'Editor/Layer/Snapping.js',
    'Editor/Control/SnappingSettings.js',
    'Editor/Control/DownloadFeature.js',
    'Editor/Control/UploadFeature.js',
    'Editor/Control/SplitFeature.js',
    'Editor/Control/UndoRedo.js',
    'Editor/Control/CADTools.js',
    'Editor/Control/ParallelDrawing.js'

], function (OpenLayers) {

/*	   var files = [
               'compat.js',
               'Editor.js',
               'Editor/Control/CleanFeature.js',
               'Editor/Control/DragFeature.js',
               'Editor/Control/DeleteFeature.js',
               'Editor/Control/DeleteAllFeatures.js',
               'Editor/Control/Dialog.js',
               'Editor/Control/DrawHole.js',
               'Editor/Control/DrawPolygon.js',
               'Editor/Control/DrawPath.js',
               'Editor/Control/DrawPoint.js',
               'Editor/Control/DrawText.js',
               'Editor/Control/DrawRegular.js',
               'Editor/Control/EditorPanel.js',
               'Editor/Control/ImportFeature.js',
               'Editor/Control/LayerSettings.js',
               'Editor/Control/MergeFeature.js',
               'Editor/Control/TransformFeature.js',
               'Editor/Control/FixedAngleDrawing.js',
               'Editor/Layer.js',
               'Editor/Layer/Snapping.js',
               'Editor/Control/SnappingSettings.js',
               'Editor/Control/DownloadFeature.js',
               'Editor/Control/UploadFeature.js',
               'Editor/Control/SplitFeature.js',
               'Editor/Control/UndoRedo.js',
               'Editor/Control/CADTools.js',
               'Editor/Control/ParallelDrawing.js'
	   ];
*/


});
